apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: temporal-frontend
  namespace: apps
spec:
  scaleTargetRef:
    name: temporal-frontend
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: cron
      metadata:
        timezone: UTC
        start: "0 0 * * 5"
        end: "0 0 * * 6"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: temporal-history
  namespace: apps
spec:
  scaleTargetRef:
    name: temporal-history
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: cron
      metadata:
        timezone: UTC
        start: "0 0 * * 5"
        end: "0 0 * * 6"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: temporal-matching
  namespace: apps
spec:
  scaleTargetRef:
    name: temporal-matching
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: cron
      metadata:
        timezone: UTC
        start: "0 0 * * 5"
        end: "0 0 * * 6"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: temporal-worker
  namespace: apps
spec:
  scaleTargetRef:
    name: temporal-worker
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: cron
      metadata:
        timezone: UTC
        start: "0 0 * * 5"
        end: "0 0 * * 6"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: smartass-subscriber
  namespace: apps
spec:
  scaleTargetRef:
    name: smartass-subscriber
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: cron
      metadata:
        timezone: UTC
        start: "30 0 * * 5"
        end: "0 0 * * 6"
        desiredReplicas: "1"
