apiVersion: v1
kind: Secret
metadata:
  name: capacitor
  namespace: apps
type: Opaque
stringData:
  registry.yaml: |
    registries: []
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capacitor
  namespace: apps
spec:
  interval: 1h
  install:
    timeout: 15m
    createNamespace: true
  upgrade:
    timeout: 15m
  chart:
    spec:
      chart: capacitor-next
      sourceRef:
        kind: HelmRepository
        name: capacitor
        namespace: flux-system
      interval: 1h
  values:
    env:
      AZURE_WORKLOAD_IDENTITY_ENABLED: "false"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
