apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
      interval: 1h
  install:
    timeout: 5m
    createNamespace: true
  upgrade:
    timeout: 5m
  values:
    resources:
      operator:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      metricServer:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      webhooks:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi
