apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - keda.yaml
  - pihole.yaml
  - traefik-config.yaml
  - postgresql.yaml
  - temporal.yaml
  - capacitor.yaml
  - smartass-subscriber.yaml
  - e-queue.yaml
  - keda-scaledobjects.yaml
