apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: apps
spec:
  interval: 1h
  install:
    timeout: 15m
    createNamespace: true
  upgrade:
    timeout: 15m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h
  values:
    fullnameOverride: postgresql
    auth:
      username: temporal
      database: temporal
      existingSecret: temporal-db
      secretKeys:
        adminPasswordKey: password
        userPasswordKey: password
    primary:
      initdb:
        scripts:
          create_visibility_db.sh: |
            #!/bin/bash
            psql -v ON_ERROR_STOP=1 --username postgres \
              --command "CREATE DATABASE temporal_visibility OWNER temporal;"
      persistence:
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
