apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
  namespace: apps
spec:
  interval: 1h
  dependsOn:
    - name: postgresql
      namespace: apps
  chart:
    spec:
      chart: temporal
      sourceRef:
        kind: HelmRepository
        name: temporal
        namespace: flux-system
      interval: 1h
  install:
    timeout: 15m
    createNamespace: true
  upgrade:
    timeout: 15m
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    server:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 300m
          memory: 1Gi
      config:
        persistence:
          defaultStore: default
          visibilityStore: visibility
          datastores:
            default:
              sql:
                pluginName: postgres12
                databaseName: temporal
                connectAddr: "postgresql:5432"
                connectProtocol: tcp
                user: temporal
                existingSecret: temporal-db
                secretKey: password
                maxConns: 20
                maxIdleConns: 20
                connMaxLifetime: 1h
            visibility:
              sql:
                pluginName: postgres12
                databaseName: temporal_visibility
                connectAddr: "postgresql:5432"
                connectProtocol: tcp
                user: temporal
                existingSecret: temporal-db
                secretKey: password
                maxConns: 20
                maxIdleConns: 20
                connMaxLifetime: 1h

    admintools:
      enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    web:
      enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
