on:
  pull_request_target:
    types: [opened, reopened]

name: Auto Assign PR Author

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  assign-author-of-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v3.0.2
