on: [push, pull_request]

name: Nix

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deadnix:
    name: Dead code (deadnix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: cachix/install-nix-action@v31
      - run: nix run nixpkgs#deadnix -- --fail .

  statix:
    name: Lint (statix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: cachix/install-nix-action@v31
      - run: nix run nixpkgs#statix -- check .

  fmt:
    name: Format (nixfmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: cachix/install-nix-action@v31
      - run: nix run nixpkgs#nixfmt -- --check $(find . -name '*.nix')

  flake-check:
    name: Flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - uses: cachix/cachix-action@v17
        with:
          name: deadnix
      - run: nix flake check
